databases:
  - name: Dynamite Postgres
    databaseName: dynamite_db
    region: singapore
    plan: free
    user: jack

services:
  - type: web
    name: current
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Dynamite Postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false